version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  isPublic: false
  labels:
    tags: []
  deprecate:
    applicationPort: '8080'
  project: ForgeCloud/saas
  projectId: 661ba589c2557ef6bcfe600f
  accountId: 642bf604797175a7ad63e335
spec:
  triggers:
    - name: kim-codefresh/new-repo
      type: git
      repo: kim-codefresh/new-repo
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /.*/gi
      branchRegexInput: regex
      gerritCIStatusLabels: []
      provider: github
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      context: github
      contexts: []
      verified: true
      status: verified
      id: 661ba59af0e9ec7f26397343
      endpoint: 'https://sandbox-1.codefresh.io/api/providers/github/hook/foVzIHMuSV'
      secret: TnWvBbXTg8m0iZ6w
  contexts:
    - kim-codefresh
    - sandbox-1-kim-aharfi
  variables:
    - key: CF_SKIP_MAIN_CLONE
      value: 'true'
    - key: FLOATING_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}'
    - key: STATIC_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}'
  specTemplate:
    location: git
    repo: kim-codefresh/pipelines
    path: customer-environment.steps.yml
    context: github
  stages: []
  concurrency: 6
  branchConcurrency: 1
  clustersInfo:
    injectAll: true
