version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  isPublic: false
  labels:
    tags: []
  deprecate:
    applicationPort: '8080'
  project: ForgeCloud/saas
  created_at: '2024-04-18T13:23:39.740Z'
  updated_at: '2024-05-01T08:45:26.928Z'
  shortName: customer-environment
  projectId: 66211eb536130bc0f5f5b6a5
  accountId: 6107f96b1895b556b7835b26
  id: 66211edbc5dc6eb292837bd8
spec:
  triggers:
    - name: deploy-services
      type: git
      repo: ForgeCloud/saas
      events:
        - push
      branchRegex: /.*/gi
      modifiedFilesGlob: >-
        {,deploy/autoaccess/**,deploy/bin/**,deploy/codefresh/*.ce.steps.yml,deploy/codefresh/auto-environment.steps.yml,deploy/codefresh/customer-environment.steps.yml,deploy/docker/fbc-tools/**,deploy/docker/util/**,deploy/kustomize/**,deploy/terraform/**,go.{mod,sum},go/common/**,tools/forge/**,go/services/customer/**,go/services/orchestration/orch-common/**,go/services/org-bootstrapper/**,go/utilities/engine-checker/**,services/cert-manager/**,services/edgedelta/**,services/elasticsearch-exporter/**,services/forgecloud/**,services/gatekeeper/**,services/haproxy/**,services/intezer/**,services/kube-state-metrics/**,services/org-filter/**,services/org-log-spewer/**,services/prometheus*/**,services/thanos/**}
      provider: github
      context: github
      verified: true
      status: verified
      id: 66212374c5dc6eb292837bd9
  contexts:
    - github
    - sdf
    - skwl
  variables:
    - key: CF_SKIP_MAIN_CLONE
      value: 'true'
    - key: FLOATING_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}'
    - key: STATIC_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}'
  specTemplate:
    location: git
    repo: ForgeCloud/saas
    path: customer-environment.steps.yml
    context: github
  stages: []
  runtimeEnvironment:
    name: kim-codefresh/kim-helm-runner
    cpu: 600m
    memory: 800Mi
  concurrency: 6
  branchConcurrency: 1
  clustersInfo:
    injectAll: true
  steps: {}

