---
version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  project: ForgeCloud/saas
  projectId: 661ba589c2557ef6bcfe600f
  accountId: 642bf604797175a7ad63e335
  created_at: '2024-04-14T09:44:55.513Z'
  updated_at: '2024-04-14T09:49:58.421Z'
  shortName: customer-environment
  deprecate: {}
  labels:
    tags: []
spec:
  triggers:
  - name: kim-codefresh/new-repo
    type: git
    repo: kim-codefresh/new-repo
    events:
    - push
    branchRegex: "/.*/gi"
    provider: github
    context: github
    id: 661ba59af0e9ec7f26397343
    endpoint: 'https://sandbox-1.codefresh.io/api/providers/github/hook/foVzIHMuSV'
    secret: TnWvBbXTg8m0iZ6w
  variables:
  - key: CF_SKIP_MAIN_CLONE
    value: 'true'
  - key: FLOATING_IMAGE_TAG
    value: "${{CF_BRANCH_TAG_NORMALIZED}}"
  - key: STATIC_IMAGE_TAG
    value: "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}"
  # FRAAS-13149: To remove this requirement
  - key: SKIP_IDENTITY_STACK_CHECK
    value: "false"
    # value: https://${{ARTIFACTORY_USERNAME}}:${{ARTIFACTORY_API_KEY}}@maven.forgerock.org/artifactory/api/go/go-virtual,https://proxy.golang.org
    # This pipeline is optimized to only build Docker images deployed by org-engine if their source has changed;
    # use the following variables to force a given stage. Default is not to force a stage unless a change has been detected.
    # - key: FORCE_BUILD_<STAGE_NAME> (eg FORCE_BUILD_ORG_ENGINE)
    #   value: "true"
  specTemplate:
    location: git
    repo: kim-codefresh/pipelines
    path: customer-environment.steps.yml
    context: github
  steps: {}
  stages: []
  concurrency: 6
  branchConcurrency: 1
