version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  project: ForgeCloud/saas
  projectId: 661ba589c2557ef6bcfe600f
  revision: 3
  accountId: 642bf604797175a7ad63e335
  created_at: '2024-04-14T09:44:55.513Z'
  updated_at: '2024-04-14T09:49:58.421Z'
  shortName: customer-environment
  deprecate: {}
  labels:
    tags: []
  originalYamlString: |+
    # More examples of Codefresh YAML can be found at
    # https://codefresh.io/docs/docs/yaml-examples/examples/

    version: "1.0"
    # Stages can help you organize your steps in stages
    stages:
      - "clone"
      - "build"
      - "test"

    steps:
      clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "kim-codefresh/new-repo"
        # CF_BRANCH value is auto set when pipeline is triggered
        # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
        revision: "${{CF_BRANCH}}"
        git: "github"
        stage: "clone"

      test:
        title: "Running test"
        type: "freestyle" # Run any command
        image: "ubuntu:latest" # The image in which command will be executed
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "ls"
        stage: "test"

  id: 661ba597c2557ef6bcfe6010
spec:
  triggers:
    - name: kim-codefresh/new-repo
      type: git
      repo: kim-codefresh/new-repo
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /.*/gi
      branchRegexInput: regex
      gerritCIStatusLabels: []
      provider: github
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      context: github
      contexts: []
      verified: true
      status: verified
      id: 661ba59af0e9ec7f26397343
      endpoint: 'https://sandbox-1.codefresh.io/api/providers/github/hook/foVzIHMuSV'
      secret: TnWvBbXTg8m0iZ6w
  clustersInfo:
    injectAll: true
  variables: []
  contexts: []
  specTemplate:
    location: git
    repo: kim-codefresh/pipelines
    path: ./customer-environment.steps.yml
    revision: main
    context: github
  steps:
    clone:
      title: Cloning repository
      type: git-clone
      repo: kim-codefresh/new-repo
      revision: '${{CF_BRANCH}}'
      git: github
      stage: clone
    test:
      title: Running test
      type: freestyle
      image: 'ubuntu:latest'
      working_directory: '${{clone}}'
      commands:
        - ls
      stage: test
  stages: []
