version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  isPublic: false
  labels:
    tags: []
  deprecate:
    applicationPort: '8080'
  project: ForgeCloud/saas
  created_at: '2024-04-18T13:23:39.740Z'
  updated_at: '2024-05-01T08:45:26.928Z'
  shortName: customer-environment
  projectId: 66211eb536130bc0f5f5b6a5
  accountId: 6107f96b1895b556b7835b26
  id: 66211edbc5dc6eb292837bd8
spec:
  triggers:
    - name: deploy-services
      type: git
      repo: ForgeCloud/saas
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /.*/gi
      branchRegexInput: regex
      gerritCIStatusLabels: []
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      provider: github
      context: github-22
      verified: true
      status: verified
      id: 66212374c5dc6eb292837bd9
      endpoint: 'https://g.codefresh.io/api/providers/github/hook/YYkig1kMMy'
  contexts:
    - github
    - sdf
    - skwl
  variables:
    - key: CF_SKIP_MAIN_CLONE
      value: 'true'
    - key: FLOATING_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}'
    - key: STATIC_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}'
  specTemplate:
    location: git
    repo: ForgeCloud/saas
    path: customer-environment.steps.yml
    context: github-1
  stages: []
  runtimeEnvironment:
    # name: kim-codefresh/kim-helm-runner
    name: arn:aws:eks:us-east-1:454353560595:cluster/kim/local-runner
    cpu: 600m
    memory: 800Mi
  concurrency: 6
  branchConcurrency: 1
  clustersInfo:
    injectAll: true
  steps: {}

