version: '1.0'
kind: pipeline
metadata:
  name: ForgeCloud/saas/customer-environment
  isPublic: false
  labels:
    tags: []
  deprecate:
    applicationPort: '8080'
    repoPipeline: true
    implicitGitCloneService:
      scm:
        provider: github
        owner:
          name: kim-aharfi
        name: saas
      context: github
  project: ForgeCloud/saas
  projectId: 5cb8378262c223370002341d
  accountId: 5a70b903592fad0001518a68
  created_at: '2019-07-02T14:43:13.277Z'
  updated_at: '2024-04-14T07:12:04.467Z'
  shortName: customer-environment
spec:
  triggers:
    - name: kim-codefresh/new-repo
      type: git
      repo: kim-codefresh/new-repo
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /.*/gi
      branchRegexInput: regex
      gerritCIStatusLabels: []
      provider: github
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      context: github
      contexts: []
      verified: true
      status: verified
      id: 661ba59af0e9ec7f26397343
      endpoint: 'https://sandbox-1.codefresh.io/api/providers/github/hook/foVzIHMuSV'
      secret: TnWvBbXTg8m0iZ6w
  contexts:
    - kim-codefresh
    - sandbox-1-kim-aharfi
  variables:
    - key: CF_SKIP_MAIN_CLONE
      value: 'true'
    - key: FLOATING_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}'
    - key: STATIC_IMAGE_TAG
      value: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_REVISION}}'
  specTemplate:
    location: git
    repo: kim-codefresh/pipelines
    path: customer-environment.steps.yml
    context: github
  stages: []
  concurrency: 6
  branchConcurrency: 1
  steps: {}
  clustersInfo:
    injectAll: true

